"""
Closed-loop waypoint position evaluator.

Compares the positions generated by plan_waypoints against the 3 user-annotated
ideal waypoint files, without running the full demo. Run after every change to
explore_costmap_map.py to measure improvement.

Run:
    python tests/evaluate_waypoint_positions.py

Output:
    - Console table: per-ideal-waypoint nearest actual + gap distance
    - Summary: hit rate and mean gap
    - evaluation_result.png saved in LOG_DIR
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(Path(__file__).parent))  # tests/ — for conftest constants
sys.path.insert(0, str(_ROOT))
sys.path.insert(0, str(_ROOT / "exploration"))  # dir containing the `exploration` package

from exploration.explore_costmap_map import (
    load_map,
    plan_waypoints,
    pixel_to_world,
    generate_candidates,
)
from conftest import REFERENCE_MAP_PGM, REFERENCE_MAP_YAML

# ── Constants (edit these to change evaluation target) ───────────────────────
LOG_DIR       = _ROOT / "tests/visual_demo_coverage/coverage_demo_log_1"
MAP_PGM       = REFERENCE_MAP_PGM
MAP_YAML      = REFERENCE_MAP_YAML
INFLATION_M   = 0.3
TOL_PX        = 20        # 1 m at 0.05 m/px
N_IDEAL_FILES = 3         # ideal_waypoints_1.csv … _3.csv
MIN_VOTES     = 2         # keep consensus positions confirmed by ≥ MIN_VOTES files

_CFG = {
    "max_detection_range": 6.0,
    "fov_horizontal": 87.0,
    "observation_rotation_increment": 30.0,
    "sampling_step_m": 3.0,
    "frontier_weight": 1.0,
    "coverage_weight": 1.0,
    "travel_cost_weight": 1.0,
    "exploration_completion_threshold": 0.90,
    "planner_coverage_warning_threshold": 0.90,
    "num_rays": 360,
}
# ─────────────────────────────────────────────────────────────────────────────


def _load_ideal_waypoints(log_dir: Path, n_files: int) -> list[tuple[int, int]]:
    """Load all ideal_waypoints_N.csv files and return (col, row) list."""
    all_points: list[tuple[int, int]] = []
    for i in range(1, n_files + 1):
        path = log_dir / f"ideal_waypoints_{i}.csv"
        if not path.exists():
            print(f"  WARNING: {path} not found — skipping")
            continue
        with open(path, newline="") as f:
            for row in csv.DictReader(f):
                all_points.append((int(row["col"]), int(row["row"])))
    return all_points


def _deduplicate(points: list[tuple[int, int]], tol_px: int, min_votes: int) -> list[tuple[int, int]]:
    """
    Cluster points within tol_px of each other and keep clusters with ≥ min_votes members.
    Returns the centroid of each qualifying cluster.
    """
    remaining = list(points)
    clusters: list[list[tuple[int, int]]] = []

    while remaining:
        seed = remaining.pop(0)
        cluster = [seed]
        sc, sr = seed
        new_remaining = []
        for p in remaining:
            pc, pr = p
            if np.hypot(pc - sc, pr - sr) <= tol_px:
                cluster.append(p)
            else:
                new_remaining.append(p)
        remaining = new_remaining
        clusters.append(cluster)

    consensus: list[tuple[int, int]] = []
    for cluster in clusters:
        if len(cluster) >= min_votes:
            cc = int(round(np.mean([p[0] for p in cluster])))
            cr = int(round(np.mean([p[1] for p in cluster])))
            consensus.append((cc, cr))
    return consensus


def main() -> None:
    print("=" * 60)
    print("Waypoint Position Evaluator")
    print("=" * 60)

    # ── Load map ──────────────────────────────────────────────────────────────
    print(f"\nLoading map from {MAP_PGM} …")
    md = load_map(MAP_PGM, MAP_YAML, INFLATION_M)
    H, W = md.pgm_array.shape
    print(f"  Map size: {W}×{H} px,  resolution: {md.resolution} m/px")

    # ── Load and deduplicate ideal waypoints ──────────────────────────────────
    print(f"\nLoading ideal waypoints from {LOG_DIR.relative_to(_ROOT)} …")
    raw_ideals = _load_ideal_waypoints(LOG_DIR, N_IDEAL_FILES)
    print(f"  Raw ideal points across {N_IDEAL_FILES} files: {len(raw_ideals)}")
    ideals = _deduplicate(raw_ideals, TOL_PX, MIN_VOTES)
    print(f"  Consensus positions (≥{MIN_VOTES} votes within {TOL_PX}px): {len(ideals)}")

    # ── Run plan_waypoints from map centre ────────────────────────────────────
    sampling_step_px = max(1, int(_CFG["sampling_step_m"] / md.resolution))
    cx, cy = W // 2, H // 2
    all_candidates = generate_candidates(md.navigable_mask, sampling_step_px)
    all_cand_arr = np.array(all_candidates, dtype=float)
    print(f"  Total candidates generated: {len(all_candidates)}")

    start_candidates = generate_candidates(md.navigable_mask,
                                           max(1, int(_CFG["max_detection_range"] / md.resolution)))
    start = min(start_candidates, key=lambda c: (c[0] - cx) ** 2 + (c[1] - cy) ** 2)
    robot_col, robot_row = start
    robot_x, robot_y = pixel_to_world(robot_col, robot_row, md.resolution,
                                      md.origin_x, md.origin_y, H)

    print(f"\nRunning plan_waypoints from robot start ({robot_col}, {robot_row}) …")
    waypoints, ratio, no_frontiers, _ = plan_waypoints(md, _CFG, robot_x, robot_y)
    actual = [(wp.col, wp.row) for wp in waypoints]
    print(f"  {len(actual)} actual waypoints generated,  coverage ratio: {ratio:.1%}")

    if not actual:
        print("  ERROR: no waypoints generated — check map and config.")
        return

    actual_arr = np.array(actual, dtype=float)   # (N, 2) col, row

    # ── Gap analysis ─────────────────────────────────────────────────────────
    print(f"\n{'#':>3}  {'ideal(c,r)':>14}  {'nearest(c,r)':>14}  {'gap_px':>7}  {'gap_m':>6}  hit")
    print("-" * 65)

    hits = 0
    miss_gaps: list[float] = []
    gap_lines: list[tuple[tuple[int,int], tuple[int,int], bool]] = []
    generation_misses = 0  # ideal not even in candidate set
    selection_misses = 0   # ideal in candidates but not selected

    for i, (ic, ir) in enumerate(ideals, start=1):
        dists = np.hypot(actual_arr[:, 0] - ic, actual_arr[:, 1] - ir)
        idx = int(np.argmin(dists))
        gap_px = float(dists[idx])
        gap_m = gap_px * md.resolution
        hit = gap_px <= TOL_PX
        if hit:
            hits += 1
            diag = ""
        else:
            miss_gaps.append(gap_px)
            # Diagnose: is this ideal position even in the candidate set?
            cand_dists = np.hypot(all_cand_arr[:, 0] - ic, all_cand_arr[:, 1] - ir)
            nearest_cand_px = float(np.min(cand_dists))
            if nearest_cand_px > TOL_PX:
                generation_misses += 1
                diag = f" [NOT A CANDIDATE — nearest cand {nearest_cand_px:.0f}px away]"
            else:
                selection_misses += 1
                diag = f" [candidate exists {nearest_cand_px:.0f}px away, not selected]"
        nc, nr = actual[idx]
        gap_lines.append(((ic, ir), (nc, nr), hit))
        mark = "✓" if hit else "✗"
        print(f"{i:>3}  ({ic:>4},{ir:>4})    ({nc:>4},{nr:>4})    {gap_px:>7.1f}  {gap_m:>6.2f}  {mark}{diag}")

    hit_rate = hits / len(ideals) if ideals else 0.0
    mean_miss = float(np.mean(miss_gaps)) if miss_gaps else 0.0
    print("-" * 65)
    print(f"\nHit rate  : {hits}/{len(ideals)} = {hit_rate:.0%}  (threshold {TOL_PX}px = {TOL_PX * md.resolution:.1f}m)")
    if miss_gaps:
        print(f"Mean gap (misses): {mean_miss:.1f} px = {mean_miss * md.resolution:.2f} m")
        print(f"  → Generation misses (ideal not a candidate): {generation_misses}")
        print(f"  → Selection misses  (candidate exists, not chosen): {selection_misses}")
    else:
        print("All ideal positions covered within tolerance.")

    # ── Visualisation ─────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(14, 10))
    ax.imshow(md.pgm_array, cmap="gray", origin="upper")

    # Navigable overlay
    nav_overlay = np.zeros((H, W, 4), dtype=np.float32)
    nav_overlay[md.navigable_mask] = [0.4, 0.6, 1.0, 0.12]
    ax.imshow(nav_overlay, origin="upper")

    # Actual waypoints
    if actual:
        ac, ar = zip(*actual)
        ax.scatter(ac, ar, s=30, color="dodgerblue", zorder=3, label="Actual waypoints")
        for j, (c, r) in enumerate(actual):
            ax.text(c + 2, r - 3, str(j), fontsize=5, color="blue", alpha=0.7)

    # Gap lines + ideal markers
    for (ic, ir), (nc, nr), hit in gap_lines:
        color = "limegreen" if hit else "red"
        ax.plot([ic, nc], [ir, nr], color=color, linewidth=0.8, alpha=0.7)

    for idx2, (ic, ir) in enumerate(ideals, start=1):
        ax.plot(ic, ir, "r*", markersize=10, zorder=4)
        ax.text(ic + 3, ir - 4, str(idx2), fontsize=7, color="red", fontweight="bold")

    ax.set_title(
        f"Hit rate: {hit_rate:.0%}  ({hits}/{len(ideals)} ideals within {TOL_PX}px = {TOL_PX*md.resolution:.1f}m)  |  "
        f"Blue=actual  Red★=ideal  Green=hit  Red=miss",
        fontsize=9,
    )
    ax.axis("off")
    plt.tight_layout()

    out_png = LOG_DIR / "evaluation_result.png"
    plt.savefig(out_png, dpi=150, bbox_inches="tight")
    print(f"\nVisualization saved → {out_png.relative_to(_ROOT)}")
    plt.show()


if __name__ == "__main__":
    main()
